# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/network_flow

GOFILES=\
	bipartite_matching.go\
	linear_programming.go\
	maximum_flow.go\
	minimum_cost_flow.go\
	transportation.go\
	transshipment.go\

include $(GOROOT)/src/Make.pkg
