# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/graph

GOFILES=\
	all_pairs_shortest_path.go\
	breadthfirst_search.go\
	depthfirst_search.go\
	minimum_spanning_tree.go\
	singlesource_shortest_path.go\

include $(GOROOT)/src/Make.pkg
