# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/path_finding

GOFILES=\
	a_search.go\
	AlphaBeta.go\
	depthfirst_search.go\
	comparison.go\
	depthfirst_search.go\
	minimax.go\
	negmax.go\
	negmax.go\

include $(GOROOT)/src/Make.pkg
