# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/comp_geometry

GOFILES=\
	convex_hull_scan.go\
	linesweep.go\
	nearest_neighbor_queries.go\
	range_queries.go\

include $(GOROOT)/src/Make.pkg
