# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/search

GOFILES=\
	binary_search.go\
	hash_search.go\
	sequential_search.go\

include $(GOROOT)/src/Make.pkg
