
include $(GOROOT)/src/Make.inc

TARG=algos/sort

GOFILES=\
	partition.go\
	counting_sort.go\
	heap_sort.go\
	insertion_sort.go\
	median_sort.go\
	quick_sort.go\
	selection_sort.go\

include $(GOROOT)/src/Make.pkg
