# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=algos/sort

GOFILES=\
	partition.go\
	bucket_sort.go\
	counting_sort.go\
	heap_sort.go\
	insertion_sort.go\
	median_sort.go\
	quick_sort.go\
	selection_sort.go\

include $(GOROOT)/src/Make.pkg
